#! /bin/sh
# Xsetup - run as root before the login dialog appears
sysresources=/etc/X11/Xresources

# merge in defaults
if [ -f "${sysresources}" ]; then
    xrdb -merge "${sysresources}"
fi
<% if @xhost -%>

xhost <%= @xhost -%>
<% end -%>

xmessage -center -file <%= @banner %>

#xconsole -geometry 480x130-0-0 -notify -verbose -fn fixed -exitOnFail -file /dev/xconsole &
